language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO="Django==1.4.8"
  - DJANGO="Django==1.5.4"
  - DJANGO="https://www.djangoproject.com/download/1.6b4/tarball/"
  - DJANGO="git+https://github.com/django/django.git"

install:
  - pip install -q $DJANGO
  - python setup.py -q install

script: cd demo && ./manage.py test webcam

matrix:
  exclude:
    - python: 2.6
      env: DJANGO="git+https://github.com/django/django.git"
