language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.4.1
  - DJANGO_VERSION=1.4.2
  - DJANGO_VERSION=1.5b1

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.pip
  - python setup.py -q install
script: cd demo && ./manage.py test webcam
