language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.2
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r -q requirements.pip
  - python setup.py -q install
script: cd demo && ./manage.py test webcam
